### PR TITLE
feat(cli): add shell completions feature and related test

### PR DESCRIPTION
**Pull request by liby**
## Description

Support for generating shell completions.

## Context
	
Closes: https://github.com/ast-grep/ast-grep/issues/589

## How I've tested my work

I have verified these changes via tested locally.

https://github.com/ast-grep/ast-grep/assets/38807139/ef8b969e-2eb5-4345-932a-be4093466a48

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
Hi, this pull request itself looks okay. But I would prefer to change `sg --generate` to `sg shell` as a subcommand.
This makes code more consistent.

**Comment by liby** [comment]
> Hi, this pull request itself looks okay. But I would prefer to change `sg --generate` to `sg shell` as a subcommand. This makes code more consistent.

Okay, if I'm willing to open another PR and make some updates.

**Comment by MariaSolOs** [comment]
Thank you @liby!

**Comment by HerringtonDarkholme** [comment]
@liby don't worry! I have already been working on it.

**Pull request merged**
