### PR TITLE
Add support for R

### PR DESCRIPTION
**Pull request by etiennebacher**
Hi, this PR adds support for R. I ran into some issues on windows which is why I added a couple of `cfg`. The tests I added are very basic, I can try to come with more elaborate ones if necessary.

## Summary by CodeRabbit

- **New Features**
  - Added support for the R programming language.
  
- **Improvements**
  - Expanded language support to include R in various functionalities such as language parsing and method execution.

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
Thanks for the contribution. But generally ast-grep does not accept [TIOBE](https://www.tiobe.com/tiobe-index/) ranking < 20 and is not maintained by [tree-sitter](https://github.com/tree-sitter) officially. 

See https://ast-grep.github.io/contributing/add-lang.html#requirements-and-constraints

**Comment by etiennebacher** [comment]
Ah ok, I should have read the docs more thoroughly

**Comment by HerringtonDarkholme** [comment]
You can still use custom language support to use R with ast-grep. See https://ast-grep.github.io/advanced/custom-language.html

**Comment by etiennebacher** [comment]
Still, I might be wrong but it seems to me that if one wants to use `ast-grep` as a library and not as a CLI tool then the language must be part of the `SupportLang` enum in order to run `ast_grep()` on it. I don't see a way to convert a `Language` object (for example the output of `tree_sitter_r::language()`) to a `SupportLang` object. Am I missing something?

**Comment by HerringtonDarkholme** [comment]
Supporting dynamic language is on the road map https://github.com/ast-grep/ast-grep/issues/1143.

**Comment by etiennebacher** [comment]
Awesome, thanks for the quick answers (and this tool)

**Pull request closed without merging**
