### PR TITLE
fix(52): normalize file path output in command line

### PR DESCRIPTION
**Pull request by SSShuai1999**
Signed-off-by: ssshuai1999 <ssshuai1999@gmail.com>

Thanks for your advice.

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
Thanks for the iteration! The code looks much nicer. Would you like to add a screenshot of the output before and after? Thanks!

**Comment by SSShuai1999** [comment]
Before: 
企业微信截图_1663898615902

After: 
企业微信截图_16638986931515

**Comment by SSShuai1999** [comment]
And also

Before:
企业微信截图_16638989489232

After:
image

**Comment by HerringtonDarkholme** [comment]
Nice work!

**Pull request merged**
