### PR TITLE
chore: add project json schema for intellisense

### PR DESCRIPTION
**Pull request by pd4d10**
For `sgconfig.yml`, related: https://github.com/ast-grep/ast-grep-vscode/issues/31

Not quite sure where it should be placed, temporarily at `schema/` folder

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
Thanks.
Can we move the json schema to vscode repo? It is more useful for editor integration.

**Comment by pd4d10** [comment]
> Can we move the json schema to vscode repo? It is more useful for editor integration.

Sure.

The reason I submit it to this repo is due to some long-term ideas: Perhaps the best approach for schema would be to generate it from Rust's types rather than maintaining it manually.

**Comment by HerringtonDarkholme** [comment]
> The reason I submit it to this repo is due to some long-term ideas: Perhaps the best approach for schema would be to generate it from Rust's types rather than maintaining it manually.

This also sounds a legitimate reason. I changed my mind. Let's still make the change in the main repo. But would you like to rename the folder name to `schemas`?

**Comment by pd4d10** [comment]
> would you like to rename the folder name to `schemas`?

Sure. Makes sense.

**Review by HerringtonDarkholme — APPROVED** [review]
Thanks. Looks good to me.

**Comment by HerringtonDarkholme** [comment]
I added one in 5fbbe2181ab24ee20de5ae73e5427a1e44fe61cd

**Pull request merged**
