### PR TITLE
feat(language): add initial support for JSON

### LINKED ISSUE #463: JSON language support
# ⭐ Suggestion

JSON language support.

# 💻 Use Cases

- Updating package.json to change versions across multiple repos.
- Eslint and other JS ecosystem tool configuration changes.

### PR DESCRIPTION
**Pull request by nissy-dev**
Fix #463 

This is my first PR in this repository. If there is anything I need to do, please feel free to let me know!

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
Hi @nissy-dev ! Thank you for your contribution. I appreciate it!

Would you like to add some test cases here? 

Example is https://github.com/ast-grep/ast-grep/blob/main/crates/language/src/css.rs 
I guess tree-sitter-json may reject pattern code like `{"key": $VALUE}`

**Comment by HerringtonDarkholme** [comment]
I understand it is hard to support JSON. Let me continue the development here.

**Comment by HerringtonDarkholme** [comment]
I created another issue https://github.com/ast-grep/ast-grep/issues/526 to track JSON support.

Let me first merge this.

Thanks!

**Review by HerringtonDarkholme — APPROVED** [review]

**Comment by nissy-dev** [comment]
@HerringtonDarkholme Sorry for the late reply as I didn't have enough time 🙇 
I really appreciate your work about adding test and moving more appropriate support.

**Pull request merged**
